# syntax=docker/dockerfile:experimental

ARG base
FROM amazon/aws-sam-cli-build-image-${base}

WORKDIR /tmp/src
RUN yum install -y pth-devel
ADD Gemfile Gemfile.lock ./
RUN bundle --deployment
ADD Rakefile versions.yaml ./
RUN --mount=type=cache,target=/opt/archives bundle exec rake build
RUN --mount=type=cache,target=/opt/archives,ro bundle exec rake package
